### ISSUE TITLE
Better loading indicator during startup

### ISSUE THREAD

**Issue by a1studmuffin** [a1studmuffin/Cataclysm-DDA-Android#11]
After the game data has installed and on all successive runs, there is a period of 10-20 seconds where the 'Z' splash screen is shown. It would be nice if this screen had a loading spinner, or at bare minimum just had a loading indicator so users don't start wondering if the app has frozen.

**Comment by Dyrewulfe** [comment]
Using -O3 to make release builds has reduced this time period significantly. This might not be necessary now.
