### ISSUE TITLE
Hardware mouse support

### ISSUE THREAD

**Issue by a1studmuffin** [a1studmuffin/Cataclysm-DDA-Android#12]
Currently all SDL_MOUSE... events are disabled in sdltiles.cpp as they were interfering with touch input. It would be nice if mouse support worked independently of touch input. This would allow users with a hardware keyboard + mouse (eg. Chromebooks) to play the game in an identical manner to the desktop version, while allowing touchscreen users to play with the new shortcut enhancements and virtual joystick/keyboard as is currently working.

**Comment by Dyrewulfe** [comment]
I can work on this, I have the technology. Question though is, easy way or hard way? With how SDL currrently handles mouse and touch, enabling both concurrently will be a nightmare. The easy way would be to have a mouse mode option, disable touch events when it's on, and let the mouse events fall through to the original mouse handling.

Edit: I can't imagine someone wanting to use a mouse and a touchscreen together.

**Comment by a1studmuffin** [comment]
Easy way sounds good to me! Down the road we could make it toggleable via #14 if that becomes a pre-game launcher of some kind.

**Comment by Dyrewulfe** [comment]
Got this fixed. I'll make a PR once the new repo is pushed. It was actually really simple: SDL_SetHint(SDL_HINT_ANDROID_SEPERATE_MOUSE_AND_TOUCH, "1"); Problem solved.

**Comment by Dyrewulfe** [comment]
While it does function, various Android devices have their own mappings for mouse buttons, which may limit the use of it. Mine, for instance​, maps all the buttons except left click to home, back, forward, etc. SDL never gets a chance to process them. I doubt we can do anything about that, shy of re-compiling everyone's Android ROM/kernel from scratch.
