### ISSUE TITLE
Choose a better default terminal width + height on first run

### ISSUE THREAD

**Issue by a1studmuffin** [a1studmuffin/Cataclysm-DDA-Android#13]
Currently the game defaults to 80x24 terminal size. While this works okay, the game runs best at higher sizes. However, we don't want to just see how many characters we can squeeze in at the device's native resolution at a 1:1 pixel ratio, since Android devices have much higher + more varied pixels-per-inch ratios compared to desktop monitors. It'd be cool if the game figured out a good default terminal size based on an integer scaling ratio so the fonts draw cleanly with no linear filtering, eg. 2x or 3x pixel size.

**Comment by Dyrewulfe** [comment]
Hmmm... So, we need to first find a means of reading the dpi, compare that against resolution, then choose an appropriate ratio?

**Comment by a1studmuffin** [comment]
Something like that yeah, though upon reflection I imagine that's probably a nightmare to get working reliably on Android. The other option is we just shoot from the hip and go with 120x36. It won't be perfect for all devices, but I think it will be a more reasonable default than 80x24, since the latter really doesn't work very well even though it's technically supported.

**Comment by Dyrewulfe** [comment]
800x480 screens are still a thing(which is kind of shameful), 120x36 would cause down-scaling with the default 8x16 font.
