### ISSUE TITLE
Add an auto-installer for soundpacks on first run

### ISSUE THREAD

**Issue by a1studmuffin** [a1studmuffin/Cataclysm-DDA-Android#14]
It'd be awesome if on first run, after game data was installed, the user was prompted if they'd like to download + install a soundpack automatically. We could pull the information from CDDA-Game-Launcher's [soundpacks.json](https://github.com/remyroy/CDDA-Game-Launcher/blob/master/data/soundpacks.json).

**Comment by Dyrewulfe** [comment]
Worth mentioning in regards to this, at one point I enabled a soundpack I'd installed myself(after doing some memory tweaking for my device, I decided to give it another go.) For some reason, this lead to excessive memory usage during the loading screen(850MB and climbing), resulting in Android killing the application. Disabling the soundpack by manually editing the options did not resolve the issue. Clearing app data fixed the issue.

I'm not certain this was a result of the soundpack or not, however.

(An actual launcher interface that runs prior to loading might be a good long-term goal. Especially if it can be used to change options in case of bugs like #5 )

**Comment by a1studmuffin** [comment]
Yeah agree that would definitely be a nice feature. A pre-game UI that allows tweaking important json options, downloading soundpacks, mods etc. Basically a touch version of CDDA-Game-Launcher's functionality with some extra stuff specific to Android.
