### ISSUE TITLE
Auto-detect Android system locale on first run

### ISSUE THREAD

**Issue by a1studmuffin** [a1studmuffin/Cataclysm-DDA-Android#16]
It would be nice if the game auto-detected the current system locale of the Android device on first run, and if a compatible translation was found it would use that instead of English. It should be possible with a JNI Java function in CataclysmDDA.java called from the C++ side, that returns the ISO language using Android's `Locale.getDefault().toString()`.

**Comment by Dyrewulfe** [comment]
I'd take this on, but my hatred for Java is reaching critical mass lately. So, if I do, it's gonna be awhile.
