### ISSUE TITLE
overmap inconsistency

### ISSUE THREAD

**Issue by Zeropol** [a1studmuffin/Cataclysm-DDA-Android#19]
The player forgot the entire overmap then the overmap may show a completely different location from where I am.
Happened with two of my games ( two differents world, lots of predownloaded mods activated ) in a week interval or so.

I first thought it was a c:dda bug ( even if I never had a comparable bug in years with windows version ), but nothing similar in CleverRaven repo issue list, at least with filter "is:open label:bug overmap". ( Two are comparables but closed years ago i dont link them ).

First time :
- I dont remember how it happened ( loading time, switching app, just ingame... )
- player "forgot" the whole overmap ( grey # )
- as I re-explore, I noticed all surface visible overmap is different ( the weirdiest thing )
- the world itself dont changed ( objects dropped, constructions etc )
- negative z-levels are forgotten but coherent with real world

second time :
- the bug showed when loading a game.
- player "forgot" the whole overmap ( grey # )
- the overmap seem to correspond to real world when re exploring. 
- the world itself is the same.
- negative z-levels are forgotten but coherent with real world

I also thought it was a new effect of scyzophrenic trait but dont find this information on the net. ( I always take scyzophrenic because my second personnality told me so and is very persuasive )
And while I played days in-game the situation dont reversed, so it has to be a bug.

I dont remember if I exited the game properly with shift-s or not so may be related to the much loved autosave on lost focus ability.

**Comment by Dyrewulfe** [comment]
There's a good chance this is related to the auto save option. Would you be willing to test if this occurs without​ it on?

**Comment by Zeropol** [comment]
ok I will play with this feature off

**Comment by Dyrewulfe** [comment]
Thank you. I suspect the game may not be finishing saving, on a focus change, prior to Android killing it. When Android requests that an app suspend/shutdown, there's a time limit to how long Android will wait before it just force kills it. The game may be getting killed mid-save on your device, which would be risky to your save files. I personally recommend using aggressive auto-save settings over quicksave on lose focus, especially on lower end devices. Something like: 2-5 minutes, 50-100 turns. Losing a couple minutes of play is better than losing your whole savefile.

**Comment by Dyrewulfe** [comment]
Has this occured again?

**Comment by Zeropol** [comment]
I didnt played much this week sorry, so no

**Comment by Zeropol** [comment]
I played a lot with "save on focus off" off, the problem didnt showed up. Any info I have can be usefull?

**Comment by Dyrewulfe** [comment]
I don't think so. It appears the auto save on focus lost is simply a risky feature
