### ISSUE TITLE
Use version.h tag to control files installation

### ISSUE THREAD

**Issue by Dyrewulfe** [a1studmuffin/Cataclysm-DDA-Android#28]
It occured to me that using the tag in version.h to control whether or not files should be re-installed seems like a better way to go about that. Thoughts?

**Comment by a1studmuffin** [comment]
Yep, completely agree. A quick fix for this could go in SplashScreen.java getVersionName(): instead of fetching the package version name, we could just use a hardcoded string that matches the current version.h. We'd just need to remember to update it when rolling out a new version of game data.

**Comment by Dyrewulfe** [comment]
Got to looking at doing this. It will require some tweaks to how the application is initialized. Need to load the libraries, then handle the install check, then start the game. It's a little extra work, but I think it'll be worth it. This will set the stage for pre-game-launch option tweaking as well.

Edit: Looking at a way to do this automatically, I mean. To avoid unnecessary re-installations, and insure proper updating while doing dev builds(where the apk version isn't going to be changing very often).
