### ISSUE TITLE
Add 0-9 digit shortcuts to pickup + drop item menus

### ISSUE THREAD

**Issue by a1studmuffin** [a1studmuffin/Cataclysm-DDA-Android#3]
When using the pickup (,) or drop (d) menus, if the user wants to specify an amount for an item, currently they must bring up the virtual keyboard. It would be nice if there were shortcuts for digits 0-9 to avoid this.

**Comment by a1studmuffin** [comment]
Manual shortcuts need to be added inside functions `inventory_drop_selector::inventory_drop_selector()` and `void Pickup::pick_up( const tripoint &pos, int min )`.

**Comment by Dyrewulfe** [comment]
I've been thinking about this. Akin to the dpad zone thing, what if we set up a pop-up number pad for this, and adv. inv., etc? That way it won't crowd out the normal hotkeys.

**Comment by a1studmuffin** [comment]
Yeah that occurred to me too, though I worry the screen might start getting a little cluttered. There's already so much going on in the main UI that it might make everything harder to read with a numpad overlaid on top. I think that's the beauty of the current shortcuts row, it's pretty minimal and out of the way, so you can concentrate on the actual game's UI.

**Comment by Dyrewulfe** [comment]
We could let the user expand/collapse it as needed, and make it optional to have it there at all. Have a small button just above the shortcut bar, anchored to a side, that when tapped expands into a 9-point pad. And detect a pinch on it to collapse it? This approach would also allow re-using the dpad code to accomplish this. The number pad is a pretty important part of the desktop version UI, IMHO.

**Comment by a1studmuffin** [comment]
Yeah that sounds good, I think it's definitely worth trying.
