### ISSUE TITLE
Phone lag when close game

### ISSUE THREAD

**Issue by Lanyaaki** [a1studmuffin/Cataclysm-DDA-Android#30]
My phone is 'Meizu MX5'，and CDDA is the latest version in google play(other version are the same).
my phone is lagging and slowing when I close the game until reboot.

I use 'top' in shell, the process 'pvr_defer_free' use a lot of CPU, this process is a part of 'PowerVR services server'(see http://dl.linux-sunxi.org/SDK/A80/A80_SDK_20140728_stripped/lichee/linux-3.4/modules/rogue_km/services/server/common/pvrsrv.c ).

Hope to fix that, thx

**Comment by Lanyaaki** [comment]
Android version 5.0.1
Helio X10 Turbo
ARM® Cortex®-A53TM 2.2GHz x 8
PowerVR G6200

**Comment by Dyrewulfe** [comment]
Have you tried using software rendering = true?

**Comment by Lanyaaki** [comment]
Its work!!!

**Comment by Lanyaaki** [comment]
Whether it can be added to the default configuration？May be other player have same problem.

**Comment by Dyrewulfe** [comment]
It is the default since v0.4.1. Your option file from the older version still had it set to false though.
