### ISSUE TITLE
UI: Some characters are missing when using non-English language

### ISSUE THREAD

**Issue by BrettDong** [a1studmuffin/Cataclysm-DDA-Android#31]
![screenshot](https://cloud.githubusercontent.com/assets/21075502/25954276/55a4d474-3698-11e7-9f6d-12f2574761ca.png)

This doesn't only happen in Chinese language but in all languages except for English.

English interface:
![screenshot-en](https://cloud.githubusercontent.com/assets/21075502/25954052/b739a620-3697-11e7-9458-13be73b4a778.png)
Spanish interface:
![screenshot-ar](https://cloud.githubusercontent.com/assets/21075502/25954126/ed807c86-3697-11e7-9cd3-a9f3612c7512.png)

The third profession _Broken Cyborg_ should be _Cíborg Rota_ in Spanish but only a single letter C appeared on the screen.

This has been confirmed to be a bug introduced in 0.4.1. No such problem occurs in 0.4.0.

**Comment by Dyrewulfe** [comment]
I'm working on it. I suspect a compilation flag broke lib-intl. Particular characters(Seems to be accented characters) are breaking the rest of line.

**Comment by Dyrewulfe** [comment]
Got it worked out.

**Comment by BrettDong** [comment]
What's the status? Is this fixed in 0.4.4?

**Comment by Dyrewulfe** [comment]
Yes, it is. At least it appears to be on both of the devices I've tested it
on.

Edit: What I mean by that is, it's hard to guarantee anything on Android, really.
