### ISSUE TITLE
Crashing on 'Profession' Screen

### ISSUE THREAD

**Issue by Deevoh** [a1studmuffin/Cataclysm-DDA-Android#52]
During character creation, I can't seem to scroll down past a certain group of classes without the game crashing on me. It's under the Profession tab and when I go down past Ranger, the app locks up and crashes. Similarly, when I scroll from the bottom and work my way up, the game will lock up and crash on Knight.

I tried creating a new world with only the DDA core and the Classic Roguelike Classes mod (which includes the ones that are crashing), and I'm still getting the crash when I scroll down to them. I've also tried changing terminal sizes to both bigger and smaller, as well as change tilesets and use default world gen values. No matter what I try, I can't seem to get past this crash. I tried replicating the crash on the latest experimental version on PC and don't have any issues. I USED to be able to select Knight and Ranger and those classes before this crash started happening too.

I'm using a Galaxy S7 Edge with the Exynos chip and on Android 7.0. I'm also using app version 0.4.5. I've tried restarting my device too and nothing worked. I also have the ChestHole soundpack installed but don't think that would affect anything.

**Comment by Dyrewulfe** [comment]
This was a bug wifh the core game. I reported it, and it's been fixed. I've been tied up switching to and setting up a new development machine, and haven't had a chance to put together an update.

**Comment by Deevoh** [comment]
Awesome, thanks. Glad to see it was caught and looking forward to the update!
