### ISSUE TITLE
updates?

### ISSUE THREAD

**Issue by qntf** [a1studmuffin/Cataclysm-DDA-Android#55]
Hello, are updates still planned?

If not, would it be as simple as merging the upstream code into here, or what do I need to be aware?

**Comment by Dyrewulfe** [comment]
I've been in a difficult life situation over the past year, resulting in my being offline for roughly half a year(No, not prison!)

I've just starting working on an update in this past hour. ETA = Heck if I know, lot of stuff to catch up on.

**Comment by qntf** [comment]
great news, thanks!
