### ISSUE TITLE
Main Menu will not load UI if device locks

### ISSUE THREAD

**Issue by chriseich21** [a1studmuffin/Cataclysm-DDA-Android#56]
**Game Version:**  0.C-22738-g9946931 _(Current Playstore development version)_
**Phone Model:** OnePlus 3T 128Gb
**OS Version:** OxygenOS 5.0.1 _(Android 8.0)_ 

**Bug/Error:**  Main Menu UI will not load if the game locks during the initial boot phase. The game must be closed and restarted in order for it to display again. However, menu is still responsive and will display the popup boxes if you select an option.

**Steps to Reproduce:**  Lock phone manually when Cataclysm splash screen first displays on device, prior to reaching main menu. Unlocking after a couple seconds displays black screen.

**Comment by a1studmuffin** [comment]
This is likely due to using software rendering. Closing this issue though as the Google Play version is no longer maintained since Android version is now part of the main repository. Latest APKs are [here](http://dev.narc.ro/cataclysm/jenkins-latest/Android/Tiles/).
