### ISSUE TITLE
Phone gets hot during gameplay, even if just sitting on the main menu

### ISSUE THREAD

**Issue by a1studmuffin** [a1studmuffin/Cataclysm-DDA-Android#6]
Reported on the forums. There appears to be a performance issue when the game is idling on the main menu. It may only occur when the software renderer is active, but not 100% sure. Perhaps we can throttle the FPS if no input was detected after a period of time.

**Comment by Dyrewulfe** [comment]
I think we can help this by using SDL_WaitEvent to block CheckMessages after a timeout has been met. It appears that the game loops for events pretty much constantly, preventing the cpu from resting. I'll look into it.

**Comment by Dyrewulfe** [comment]
I'm playing with this right now, and it definitely reduces cpu usage when idle. I'm having an issue with keeping weather animations functioning while doing so, though.

**Comment by Dyrewulfe** [comment]
Got it worked out. The way animations are handled in the game reduces the overall effectiveness of this, we may need to modify that. For now though, I'm going to triple the maximum animation delay. 

CPU usage is near minimal when idle and not animating, thougn.

**Comment by a1studmuffin** [comment]
Cool, that sounds like a reasonable compromise for more battery life! :)

**Comment by Dyrewulfe** [comment]
Re-opening until I can resolve input lag issues.
