### ISSUE TITLE
Is this abandoned?

### ISSUE THREAD

**Issue by BorkBorkGoesTheCode** [a1studmuffin/Cataclysm-DDA-Android#60]
@a1studmuffin @Wulfe813 will you update this fork?

**Comment by a1studmuffin** [comment]
Unfortunately I don't have any immediate plans to keep the branch updated due to time constraints. I was thinking whenever 0.D stable comes out I would do a port of that when I find the time, as this would likely be mostly a one-off to get up and running. Not sure if @Wulfe813 has any plans for this branch.

**Comment by chriseich21** [comment]
It recently was updated in the Playstore, I think February 21, 2018 but the github repo just hasn't been updated yet. I think it was only a small bug/crash fix though.

**Comment by a1studmuffin** [comment]
Good summary of status here:
https://www.reddit.com/r/cataclysmdda/comments/8095ui/status_of_android_port_development/

In short, despite the Play store being updated, it's unlikely we'll see
this fork being maintained in the future. Of course I would like to leave
it here for any future CDDA archaeologists to use as reference. Perhaps I
could add a note to the GitHub readme explaining this?

**Comment by chriseich21** [comment]
@a1studmuffin Sorry read the reddit post now, so Wulfe will update periodically so core game will get new content like PC, but the current work on anything Android related is on hold while Wulfe implements the new UI? Which by the way, thanks a lot, CDDA really needs to get to 0.D, experimental is pretty stable always but I think newcomers go to stable and there's tons of QoL changes over 0.C (auto loading quiver omg). Also thanks for work on porting this over, probably sad, but I play it a lot more on my phone than PC...

**Comment by a1studmuffin** [comment]
Final comment in case anyone ends up here from Google - we've now got an official Android build of Cataclysm: Dark Days Ahead! 🎉 Visit the [official repository](http://github.com/CleverRaven/Cataclysm-DDA/) or [grab the latest APK](http://dev.narc.ro/cataclysm/jenkins-latest/Android/Tiles/).
