### ISSUE TITLE
Game crash everytime when loses focus

### ISSUE THREAD

**Issue by MaysaChan** [a1studmuffin/Cataclysm-DDA-Android#61]
This issues has been submitted before but due to developer are too busy, the previous submission maybe couldn't reach him. Game crash every single time when app loses focus, autosave most of the are not working 

Please, Fix this when you get time @a1studmuffin

**Comment by Edmund-Shi** [comment]
Software render is not stable. In Setting -> Option -> Graphics -> Software rendering, you should turn off software rendering and restart game.

**Comment by MaysaChan** [comment]
@Edmund-Shi that fix the problem completely 
Thank you very much ^^

**Comment by Vuthric** [comment]
@Edmund-Shi 
Thanks you so much how can I repay you
