### ISSUE TITLE
Add an easier way to reset all shortcuts for the current screen

### ISSUE THREAD

**Issue by a1studmuffin** [a1studmuffin/Cataclysm-DDA-Android#7]
It would be nice if users had a simple way to reset the shortcuts for the current screen that doesn't require flicking up on every shortcut to remove them all.

**Comment by Dyrewulfe** [comment]
It would be nice, and I've kept thinking at it. Just not getting any inspiration on this one. There's always an issue with the approaches I've had come to mind.
