### ISSUE TITLE
Add an alternative 'Screen Edges' touch input method for directional input + confirm + back actions

### ISSUE THREAD

**Issue by a1studmuffin** [a1studmuffin/Cataclysm-DDA-Android#8]
Currently the Virtual Joystick is the only method (aside from the virtual keyboard) for directional input (swiping in a direction), tapping to confirm and double-tapping to go back.

Some users don't like swiping and would prefer an alternative input method using screen edges. Effectively the screen would be divided into a 3x3 grid. Tapping a screen edge would move in that direction (like a numpad). Tapping the screen center would confirm (Enter key) or wait a turn ('.' when in-game). Tapping + holding would repeat the action until released (except for the confirm action). Double-tapping the screen center would go back (ESC). This would offer very similar functionality to the existing virtual joystick, but avoids the need to swipe. 

For low-spec devices this input method would also avoid the issue of a low frame rate = inconsistent swipe detection. Particularly important while driving, or choosing where to light a fire.

**Comment by Dyrewulfe** [comment]
I'd suggest these additions. Allow the user to scale and position the grid to their liking, and optionally display an outline with variable transparency. We'll get two features for one that way. Screen edge style, and a d-pad.

**Comment by a1studmuffin** [comment]
Yep that all sounds good to me.

**Comment by a1studmuffin** [comment]
I've got this working locally. I've added a 'touch input method' option to choose between 'Virtual Joystick' (current behaviour) or 'Virtual D-pad' (a 3x3 grid overlay). When the virtual d-Pad is active, the 3x3 grid is drawn as a transparent overlay. By default it fills the bottom right quarter of the screen. There are some additional options to customize the D-pad, including opacity (0% = invisible), left/right/top/bottom margin (as % of screen length), and touch behaviour outside the d-Pad (toggle between no effect, or behave the same as the center of the d-Pad button).

The only feedback this doesn't address is the request from some users to be able to toggle quickly between the two methods, or possibly even have both active at once. For example, you could tuck the d-pad in the bottom right corner for times you need precise directional input (eg. choosing where to light a fire, driving a car), but swiping outside the d-Pad would enable the virtual joystick. I'll have a further think about this.
